---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 110, host: 8110, auto_correct: true}]
  - ["forwarded_port", {guest: 995, host: 8995, auto_correct: true}]
  - ["forwarded_port", {guest: 143, host: 8143, auto_correct: true}]
  - ["forwarded_port", {guest: 993, host: 8993, auto_correct: true}]

provisioner:
  name: chef_zero
  data_bags_path: ./test/data_bags
  # client_rb:
  #   treat_deprecation_warnings_as_errors: true # WiP on some depends

platforms:
- name: centos-7.9
- name: centos-stream-8
- name: centos-stream-9
- name: fedora-36
- name: fedora-37
- name: oracle-7.4
- name: oracle-7.9
# - name: oracle-8.7 # fail: no image
- name: oracle-9.1
- name: debian-10.13
  run_list: recipe[apt]
- name: debian-11.6
  run_list: recipe[apt]
- name: ubuntu-18.04
  run_list: recipe[apt]
- name: ubuntu-20.04
  run_list: recipe[apt]
- name: ubuntu-22.04
  run_list: recipe[apt]
- name: opensuse-leap-15

suites:
- name: default
  run_list:
  - recipe[dovecot_test]
- name: ldap
  run_list:
  - recipe[dovecot_test::ldap]
  excludes:
    # does not use (deprecated) slapd.conf anymore,
    # and openldap cookbook is not up-to-date with this change yet
    - fedora-36
    - fedora-37
    - ubuntu-22.04
    # FIXME: broken mirror
    - centos-stream-8
    - oracle-9.1
    # FIXME: ldap_spec fails
    - centos-7.9
    - centos-stream-9
    - oracle-7.4
    - oracle-7.9
    - ubuntu-18.04
- name: attributes
  run_list:
  - recipe[dovecot_test::attributes]
- name: create_pwfile
  run_list:
  - recipe[dovecot_test::create_pwfile]
