---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 110, host: 8110, auto_correct: true}]
  - ["forwarded_port", {guest: 995, host: 8995, auto_correct: true}]
  - ["forwarded_port", {guest: 143, host: 8143, auto_correct: true}]
  - ["forwarded_port", {guest: 993, host: 8993, auto_correct: true}]

provisioner:
  name: chef_zero
  data_bags_path: ./test/data_bags
  # client_rb:
  #   treat_deprecation_warnings_as_errors: true # WiP on some depends

platforms:
- name: centos-6.7
- name: centos-7.2
- name: centos-7.4
- name: centos-7.5
- name: fedora-26
- name: fedora-28
- name: oracle-6.9
- name: oracle-7.4
- name: debian-7.11
  run_list: recipe[apt]
- name: debian-8.9
  run_list: recipe[apt]
- name: debian-8.10
  run_list: recipe[apt]
- name: debian-9.2
  run_list: recipe[apt]
- name: debian-9.3
  run_list: recipe[apt]
- name: debian-9.4
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-16.04
  run_list: recipe[apt]
- name: ubuntu-18.04
  run_list: recipe[apt]
- name: opensuse-leap-42

suites:
- name: default
  run_list:
  - recipe[dovecot_test]
- name: ldap
  run_list:
  - recipe[dovecot_test::ldap]
  excludes:
    # does not use (deprecated) slapd.conf anymore,
    # and openldap cookbook is not up-to-date with this change yet
    - fedora-26
    - fedora-28
- name: attributes
  run_list:
  - recipe[dovecot_test::attributes]
- name: create_pwfile
  run_list:
  - recipe[dovecot_test::create_pwfile]
  excludes:
  # old versions of Dovecot does not support default_field_values
  - centos-6.7
  - oracle-6.9
  # by default does not have 'snakeoil' self-signed cert and key
  - debian-8.9
  - debian-8.10
  - debian-9.2
  - debian-9.3
  - debian-9.4
