inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
  - .kitchen
  - vendor/**/*
Metrics/ModuleLength:
  Max: 121

Style/CommentedKeyword:
  Enabled: False

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Max: 50

Layout/HeredocIndentation:
  Enabled: False

Naming/HeredocDelimiterNaming:
  Enabled: False

Style/MultilineIfModifier:
  Enabled: False

Naming/MethodParameterName:
  Enabled: False

Layout/ClosingHeredocIndentation:
  Enabled: False
