rvm: 2.5

sudo: required

services: docker

env:
  global:
  - CHEF_VERSION="~> 14.0"
  matrix:
  - TESTS="style unit"
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - TESTS="integration[default-centos-79,verify]"
  - TESTS="integration[default-centos-stream-8,verify]"
  - TESTS="integration[default-centos-stream-9,verify]"
  - TESTS="integration[default-fedora-36,verify]"
  - TESTS="integration[default-fedora-37,verify]"
  - TESTS="integration[default-oracle-74,verify]"
  - TESTS="integration[default-oracle-79,verify]"
  - TESTS="integration[default-oracle-91,verify]"
  - TESTS="integration[default-debian-1013,verify]"
  - TESTS="integration[default-debian-116,verify]"
  - TESTS="integration[default-ubuntu-1804,verify]"
  - TESTS="integration[default-ubuntu-2004,verify]"
  - TESTS="integration[default-ubuntu-2204,verify]"
  - TESTS="integration[default-opensuse-leap-15,verify]"
  - TESTS="integration[ldap-debian-1013,verify]"
  - TESTS="integration[ldap-debian-116,verify]"
  - TESTS="integration[ldap-ubuntu-2004,verify]"
  - TESTS="integration[ldap-opensuse-leap-15,verify]"
  - TESTS="integration[attributes-centos-79,verify]"
  - TESTS="integration[attributes-centos-stream-8,verify]"
  - TESTS="integration[attributes-centos-stream-9,verify]"
  - TESTS="integration[attributes-fedora-36,verify]"
  - TESTS="integration[attributes-fedora-37,verify]"
  - TESTS="integration[attributes-oracle-74,verify]"
  - TESTS="integration[attributes-oracle-79,verify]"
  - TESTS="integration[attributes-oracle-91,verify]"
  - TESTS="integration[attributes-debian-1013,verify]"
  - TESTS="integration[attributes-debian-116,verify]"
  - TESTS="integration[attributes-ubuntu-1804,verify]"
  - TESTS="integration[attributes-ubuntu-2004,verify]"
  - TESTS="integration[attributes-ubuntu-2204,verify]"
  - TESTS="integration[attributes-opensuse-leap-15,verify]"
  - TESTS="integration[create-pwfile-centos-79,verify]"
  - TESTS="integration[create-pwfile-centos-stream-8,verify]"
  - TESTS="integration[create-pwfile-centos-stream-9,verify]"
  - TESTS="integration[create-pwfile-fedora-36,verify]"
  - TESTS="integration[create-pwfile-fedora-37,verify]"
  - TESTS="integration[create-pwfile-oracle-74,verify]"
  - TESTS="integration[create-pwfile-oracle-79,verify]"
  - TESTS="integration[create-pwfile-oracle-91,verify]"
  - TESTS="integration[create-pwfile-debian-1013,verify]"
  - TESTS="integration[create-pwfile-debian-116,verify]"
  - TESTS="integration[create-pwfile-ubuntu-1804,verify]"
  - TESTS="integration[create-pwfile-ubuntu-2004,verify]"
  - TESTS="integration[create-pwfile-ubuntu-2204,verify]"
  - TESTS="integration[create-pwfile-opensuse-leap-15,verify]"

before_install:
- chef --version &> /dev/null || curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 3.1.0
- eval "$(/opt/chefdk/bin/chef shell-init bash)"

install:
- sudo chef exec gem update --system 2.7.5
- chef exec bundle install --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

before_script:
# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- chef --version
- cookstyle --version
- rubocop --version

script: travis_retry chef exec bundle exec rake $TESTS
