rvm: 2.5

sudo: required

services: docker

env:
  global:
  - CHEF_VERSION="~> 14.0"
  matrix:
  - TESTS="style unit"
# Split up the test-kitchen run to avoid exceeding 50 minutes:
  - TESTS="integration[default-centos-6,verify]"
  - TESTS="integration[default-centos-7,verify]"
  - TESTS="integration[default-debian-7,verify]"
  - TESTS="integration[default-debian-8,verify]"
  - TESTS="integration[default-debian-9,verify]"
  - TESTS="integration[default-fedora-26,verify]"
  - TESTS="integration[default-fedora-28,verify]" 
  - TESTS="integration[default-oracle-6,verify]"
  - TESTS="integration[default-oracle-7,verify]"
  - TESTS="integration[default-ubuntu-1404,verify]"
  - TESTS="integration[default-ubuntu-1604,verify]"
  - TESTS="integration[default-ubuntu-1804,verify]"
  - TESTS="integration[default-opensuse-leap-42,verify]"
  - TESTS="integration[ldap-centos-6,verify]"
  - TESTS="integration[ldap-centos-7,verify]"
  - TESTS="integration[ldap-debian-7,verify]"
  - TESTS="integration[ldap-debian-8,verify]"
  - TESTS="integration[ldap-debian-9,verify]"
  - TESTS="integration[ldap-oracle-6,verify]"
  - TESTS="integration[ldap-oracle-7,verify]"
  - TESTS="integration[ldap-ubuntu-1404,verify]"
  - TESTS="integration[ldap-ubuntu-1604,verify]"
  - TESTS="integration[ldap-ubuntu-1804,verify]"
  - TESTS="integration[ldap-opensuse-leap-42,verify]"
  - TESTS="integration[attributes-centos-6,verify]"
  - TESTS="integration[attributes-centos-7,verify]"
  - TESTS="integration[attributes-debian-7,verify]"
  - TESTS="integration[attributes-debian-8,verify]"
  - TESTS="integration[attributes-debian-9,verify]"
  - TESTS="integration[attributes-fedora-26,verify]"
  - TESTS="integration[attributes-fedora-28,verify]" 
  - TESTS="integration[attributes-oracle-6,verify]"
  - TESTS="integration[attributes-oracle-7,verify]"
  - TESTS="integration[attributes-ubuntu-1404,verify]"
  - TESTS="integration[attributes-ubuntu-1604,verify]"
  - TESTS="integration[attributes-ubuntu-1804,verify]"
  - TESTS="integration[attributes-opensuse-leap-42,verify]"
  - TESTS="integration[create-pwfile-centos-7,verify]"
  - TESTS="integration[create-pwfile-debian-7,verify]"
  - TESTS="integration[create-pwfile-oracle-7,verify]"
  - TESTS="integration[create-pwfile-ubuntu-1404,verify]"
  - TESTS="integration[create-pwfile-ubuntu-1604,verify]"
  - TESTS="integration[create-pwfile-ubuntu-1804,verify]"
  - TESTS="integration[create-pwfile-opensuse-leap-42,verify]"

before_install:
- chef --version &> /dev/null || curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 3.1.0
- eval "$(/opt/chefdk/bin/chef shell-init bash)"

install:
- sudo chef exec gem update --system 2.7.5
- chef exec bundle install --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

before_script:
# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- chef --version
- cookstyle --version
- foodcritic --version

script: travis_retry chef exec bundle exec rake $TESTS
